### ISSUE TITLE
timers.enroll() is deprecated

### ISSUE THREAD

**Issue by muturgan** [mysqljs/mysql#2034] opened 2018-05-31 06:34 UTC
windows
node 10.1.0
mysql 2.15.0 (or 2.14.1 in promise-mysql)

The first (and only the first) querry to database lead to sequential messages in console:
(node:xxx) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:xxx) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

After it i got my result from database.
It's not a probleb, but in 1% of trying it leads to crashing server.

I didn't think to copy error message that time.

**Comment by erwinw** [comment] 2018-05-31 09:16
Duplicate of #2003 ?

**Comment by muturgan** [comment] 2018-05-31 12:15
absolutely!

**Closed** 2018-05-31 12:21 UTC
