### ISSUE TITLE
no callbacks when long uptime

### ISSUE THREAD

**Issue by dvlprs** [mysqljs/mysql#1517] opened 2016-09-14 09:10 UTC
Hi everyone, 

I collect some data into an array in realtime. Then there's code that kicks in every 30 seconds and dumps that data into a database table. This is some kind of a buffer I made to avoid calling and writing to database every time new data comes in. 

I create a pool first:

```js
var db_config={
    connectionLimit : 1,
    host     : 'remote.example.com',
    user     : 'user',
    password : 'password',
    database : 'database',
    //timezone : 'utc'
};
var connection = mysql.createPool(db_config);
connection.query("SET time_zone = '+00:00';");
```

And here's the code:
```js
setInterval(function() {
        console.log(new Date().getTime()+' 1. TRIGGERED values.length:'+values.length);
        if (values.length>0) {
            var sql = "INSERT INTO log (time, key, value) VALUES ?";
            connection.query(sql, [values], function(err, results){
                if (!err) {
                    console.log(new Date().getTime()+' 2. MYSQL CALLBACK values.length:'+values.length);
                } else {
                    console.log(new Date().getTime()+' 3. MYSQL ERROR'+err);
                }
            });
        } else {
            console.log(new Date().getTime()+' NO VALUES');
        }
}, 30000);
```

At first it worked just fine. This is a development server so I restarted node from time to time. Then I left for about 1 month and when I came back I found out that the last time the DB table was updated was approximately 2 weeks after the script was started. I logged on to the server and checked the node output. I can see that *1.* is still being triggered and the `values.length` is greater than 0, but there are no callbacks (*2.*) or errors (*3.*) anymore. I checked `netstat` and I can see that node still has a connection established to `remote.example.com:3306`. I didn't restart node or launch node inspector yet because that'd reset the current state.

I have no idea what this might be. Please help

mysql: 2.9.0
node: 4.1.2
os: debian 7.8

**Comment by sidorares** [comment] 2016-09-14 23:37
In this type of use ( very long running, low number of queries over time ) I'd rather create/dispose connection each time you do a query. Not having error feels strange though - if the server has disconnected you would see it in callback error

**Comment by dvlprs** [comment] 2016-09-15 14:31
Is there any information which would help debugging this that I could get from the environment while the script is running? Wanted to make sure before I restart it

**Comment by dougwilson** [comment] 2016-09-15 16:31
Hi @dvlprs , if you don't attach a debugger, one thing you can try is using Linux to kil that TCP connection your Node.js script has with the MySQL server, and seeing if the script ends up resuming with those callbacks. That would give us a place to start looking to see if we can figure out some kind of reproduction.

**Comment by dvlprs** [comment] 2016-09-15 16:43
Hi @dougwilson, thank you for replying. I logged on to the server to try doing [`tcpkill`](http://unix.stackexchange.com/questions/71940/killing-tcp-connection-in-linux) as you suggested but the node process has crashed. I restarted it and the mysql callback is there again. 

I'm going to leave it running in the background, is there something I should put into that function to make it easier to debug the issue in case it happens again?

**Comment by dougwilson** [comment] 2016-09-15 17:14
Hi @dvlprs , did the node process crash before you after you used `tcpkill`?

You can try putting `debug: true` in your connection options (`db_config` variable) and that should print out all the things that go and come over the MySQL connection. That is the most the module currently has in built-in debugging and if it hangs, seeing the last things printed may help a lot.

**Comment by dvlprs** [comment] 2016-09-16 10:56
The node process crashed before I had a chance to do `tcpkill`. There must've been some sort of a memory leak, probably had something to do with all that data it was trying to write to the DB but couldn't.

Thank you for suggesting `debug: true`, is there any way I could forward that info into a file like `mysqljs.log`? Because I might not be able to find it in stdout.

**Comment by dougwilson** [comment] 2016-09-18 07:53
Hi @dvlprs, currently the `debug` stuff all uses `console.log` internally. You can use I/O redirection to redirect that to a file, of course, you can overwrite `console.log` to make it output to a file, or you can edit the `mysql` source code, since it's not flexible (yet?).

**Comment by dougwilson** [comment] 2016-10-27 02:52
Hi @dvlprs, I hope it's OK if I close this issue, as it has been a bit over a month and without any information to look into, I'm not sure if there is anything for me to do. Let me know if you have anything and I can re-open!

**Closed by dougwilson** 2016-10-27 02:52 UTC

**Comment by dvlprs** [comment] 2016-10-27 19:21
@dougwilson sorry about the inactivity, I was assigned to a different project that has a higher priority so I didn't have a chance to look into this. I should've closed the issue myself. 

I will surely get back to you when/if I have more info. 

Thanks again!

**Comment by dougwilson** [comment] 2016-10-28 01:14
Ah, yea, stuff happens :) I'm sure if we see this pop up again, we should get it fixed. But if not, and you end up back on this again, please drop by!
