### ISSUE TITLE
Poolcluster  Connection pooling problem

### ISSUE THREAD

**Issue by c-y-q** [mysqljs/mysql#2364] opened 2020-06-19 09:37 UTC
1. Can you increase the number of connections in the automatic maintenance connection pool 
   function?
2. when use PoolCluster,connection.release() is not work;
3.when l use PoolCluster.end(),  it closes all connections,All the mysql connections are closed, 
   Other running query statements are all wrong and All running transaction operations also report 
  errors.
that's all.

l need your big help

**Comment by dougwilson** [comment] 2020-06-19 13:03
Hi @c-y-q !

> Can you increase the number of connections in the automatic maintenance connection pool function?

I'm not sure what you mean by "the automatic maintenance connection pool function", but you can find the list of pool options at https://github.com/mysqljs/mysql#pool-options and the one you are looking for is `connectionLimit`.

> when use PoolCluster,connection.release() is not work;

Please provide code the reproduces your issue, as my testing just now and our test suite shows otherwise. If you can provide a way to demonstrate, we can more easily determine what the issue is and fix it.

> when l use PoolCluster.end(), it closes all connections,All the mysql connections are closed,
Other running query statements are all wrong and All running transaction operations also report
errors.

This is correct. See https://github.com/mysqljs/mysql#closing-all-the-connections-in-a-pool . Do not close your pool if you still are using the connections. You need to close it when you are finished with it. If you close it early, this module will alert you with errors that you are closing it too early, as you experienced.

**Comment by c-y-q** [comment] 2020-06-20 03:07
@dougwilson 
here  is my code: 
1. mysqlUtil.js
    const mysql = require("mysql");
    class MysqlModel {
         constructor() {
        // this.mysqlConfig = config.mysql;
         }
    /**
     * 实例化mysql
     */
    mysqlInstance() {
        const poolCluster = mysql.createPoolCluster({
            removeNodeErrorCount: 1, // Remove the node immediately when connection fails.
            defaultSelector: "RR" //RR,RANDOM,ORDER
        });
        const mysqlNodes = {
            node1: {
                host: "mysql_host,
                port: 3306,
                user: "root",
                password: "mysql_password",
                database: "my_test_database",
                charset: "utf8",
                waitForConnections: true,
                connectionLimit: 10, 
                queueLimit: 0 
            },
            node2: {
                host: "mysql_host",
                port: 3306,
                user: "root",
                password: "mysql_password",
                database: "my_test_database",
                charset: "utf8",
                waitForConnections: true,
                connectionLimit: 10, 
                queueLimit: 0 
            },
            node3: {
                host: "mysql_host",
                port: 3306,
                user: "root",
                password: "mysql_password",
                database: "my_test_database",
                charset: "utf8",
                waitForConnections: true,
                connectionLimit: 10, 
                queueLimit: 0 
            }
        };
        for (let node in mysqlNodes) {
            poolCluster.add(`${node}`, mysqlNodes[`${node}`]);
        }
        return new Promise((resolve, reject) => {

            poolCluster.getConnection(function (err, connection) {
                if (err) {
                    reject(err);
                } else {
                    resolve([
                        connection,
                        poolCluster
                    ]);
                }
            })
        })
    }

    
    async getConnection() {
        return await this.mysqlInstance();
    }
}

async function mysqlDBUtil() {
    try {
        const db = new MysqlModel();
        const [conn, pool] = await db.getConnection();
        const rollback = async function () {
            conn.rollback();
        }

        const query = function (sql, options) {
            return new Promise((resolve, reject) => {
                conn.query(sql, options, function (error, results, fields) {
                    if (error) {
                        reject(error);
                    } else {
                        resolve(results);
                    }
                })
            })
        }

       
        const commit = function () {
            return new Promise((resolve, reject) => {
                conn.commit(function (err) {
                    if (err) {
                        reject(err);
                    }
                    resolve(true);
                   
                });
            })
        }
       
        const close = async function () {
           conn.release();// conn.release() does not work,so l had used pool.end();
        }

        const beginTransaction = async function () {
            conn.beginTransaction();
        }


        pool.on('release', function (connection)  { //**conn.release() does not work,so it also not work**;
            console.log('Connection %d released', connection.threadId);
        });

        return {
            rollback,
            commit,
            close,
            query,
            beginTransaction
        }
    } catch (error) {
        throw error;
    }
}
module.exports = mysqlDBUtil;

2. this is router code:
    var express = require("express");
    var router = express.Router();
    const mysqlUtil = require("./mysqlUtil");
  router.get("/", async function (req, res, next) {
     for (let i = 0; i < 5000; i++) {
          const db = await mysqlUtil();
          const sql = "select * from wx_pg_user limit 0,1";
          const result = await db.query(sql);
          await db.close();
          console.log(i, result)
     }
      res.send('ok');
});

module.exports = router;

3. l use connecntion.release() get the test result:  Too many connections
![mysql_question](https://user-images.githubusercontent.com/24750024/85189005-92e1a780-b2dd-11ea-8aac-a6c66f4b689e.png)

**Closed** 2020-06-20 06:24 UTC
Labels: needs more info
