### ISSUE TITLE
Return array of arrays rather than objects

### ISSUE THREAD

**Issue by DedDorito** [mysqljs/mysql#1784] opened 2017-07-25 18:30 UTC
This is half feature request / half question.

First, is it possible to return an array of arrays rather than an array of objects?  It doesn't appear this functionality is officially supported.  Is there a slight hack that I could implement myself to achieve this?

Second, how are the column names added?  Does the query actually return the column names for every single row, or does the query simply return the headers once and this library duplicates them while constructing the object for each row?

Thanks!

EDIT:  To clarify about the "slight hack" comment, I realize I can do something like `rows.map(row => row.column)` but I was trying to avoid the slight overhead of constructing the array of objects in the first place only to map it back to an array.

**Comment by sidorares** [comment] 2017-07-25 23:45
Duplicate of #1637

**Closed by sidorares** 2017-07-25 23:45 UTC

**Comment by sidorares** [comment] 2017-07-26 00:32
>  Second, how are the column names added? Does the query actually return the column names for every single row, or does the query simply return the headers once and this library duplicates them while constructing the object for each row?

No, it returns fields packets first, and then rows: http://web.archive.org/web/20160604100755/http://dev.mysql.com/doc/internals/en/com-query-response.html#packet-COM_QUERY_Response

![graphviz-3ab2ba81081a7f3cc556d11fd09f50341bba6f15](https://user-images.githubusercontent.com/173025/28599410-abc8dd38-71ed-11e7-9a0a-4a930a29c033.png)

**Comment by DedDorito** [comment] 2017-07-26 02:42
Awesome, thanks for explaining that.
