### ISSUE TITLE
DELIMITER CREATE PROCEDURE is not working

### ISSUE THREAD

**Issue by lagden** [mysqljs/mysql#1884] opened 2017-11-28 02:42 UTC
Hi,

I have a script to load data from sql file...
If contains `DELIMITER CREATE PROCEDURE` in sql file, I've got an error:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER ;;
CREATE DEFINER=`root`@`localhost` PROCEDURE `findStuff`(IN _c' at...
```

This sql file is generated by `mysqldump` command!!

I made a gist: https://gist.github.com/lagden/237481c44b44353f69c2b45d68410db3

There are 4 files:

```
- data.sql - sql dump
- db.js    - script to load sql dump
- query.js - run the query (lib)
- pool.js  - createPool connection (lib)
```

Regards

**Comment by dougwilson** [comment] 2017-11-28 02:47
Hi @lagden this is because `DELIMITER` is not a SQL keyword, it is a comment to the `mysql` command line client to change it's delimiter interpretation. This is a driver, simply sending whatever text you provide as-is to your MySQL server, in which case your MySQL server is rejecting your query with that message because it doesn't understand `DELIMITER` statement.

Maybe this library could support it is someone wanted to make a PR. Issue #1683 is tracking this, so closing as duplicate of #1683

**Closed by dougwilson** 2017-11-28 02:47 UTC

**Comment by lagden** [comment] 2017-11-28 02:50
Ok, thanks...
I will see there...
