### ISSUE TITLE
Field as JSON datatype  but why query Data as String datatype

### ISSUE THREAD

**Issue by zeing** [mysqljs/mysql#1783] opened 2017-07-25 04:07 UTC
my Field as JSON datatype  but why query Data as String datatype
I use MYSQL 5.7.18 
My database info 
![image](https://user-images.githubusercontent.com/20161393/28555009-1f35ad54-7127-11e7-8ae1-4987bf157bcc.png)
My table and field type
![image](https://user-images.githubusercontent.com/20161393/28555021-37647734-7127-11e7-923b-fc7c03315500.png)
e.q. data 
`prefix : {"en": "Dr.", "low": "dr."}
firstname: {"en": "Eing", "low": "eing"}
`

My code connection from nodejs 
````
const   mysql = require('mysql');

var connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'test',
    charset: 'utf8_unicode_ci',
    typeCast: false
});

function createRequest(command, callback,opt) {
    connection.query(command,opt, function (err, results, fields) {
        if(!err) {
            var Data;
            Data = JSON.stringify(results);
            if(typeof callback == "function") {
                callback(null,Data)
            } else
                return Data
        } else {
            callback(err,{});
        }
    });

}

module.exports = {
    createRequest : createRequest
};
````
Original results is 
` [ RowDataPacket {
    id: 1,
    user_id: 4,
    prefix: '{"en": "Dr.", "low": "dr."}',
    firstname: ' {"en": "Eing", "low": "eing"}',
}]`

i use JSON.stringify then Data as 
`[{"id":1,"user_id":4,"prefix":"{\"en\": \"Dr.\", \"low\": \"dr.\"}","firstname":"{\"en\": \"Eing\", \"low\": \"eing\"}"`

Why some field which have JSON type in Database but it is String after query

**Comment by dougwilson** [comment] 2017-07-25 04:09
This is because only the following type castings exist: https://github.com/mysqljs/mysql#type-casting

**Comment by dougwilson** [comment] 2017-07-25 04:10
Duplicate of #1267

**Closed by dougwilson** 2017-07-25 04:10 UTC
Labels: question

**Comment by zeing** [comment] 2017-07-25 04:19
thank you
