### ISSUE TITLE
[pool] know when a connection is kept for "too long"

### ISSUE THREAD

**Issue by dresende** [mysqljs/mysql#1449] opened 2016-06-21 20:36 UTC
I have a project where I have an abstraction over this package and it seems that from time to time I loose the ability to open a web view to the application because it is waiting for a free connection from the poll and none is free.

I inspected the database and the connections are there but in sleep. So perhaps there's something with the application not releasing connections back to the poll. I was wondering if anyone has a good idea to debug this. I was thinking about having some kind of event triggered when a connection is requested and not released in a certain amount of time (seconds). Perhaps this feature is useful for others, I'm not sure about performance and complexity on detecting timeouts..

Anyone has a better idea?

**Comment by dresende** [comment] 2016-06-21 20:37
The application is proprietary and big, that's why I'm looking for something that I can do using `mysql` and not placing probes all over the app code..

**Comment by dresende** [comment] 2016-06-21 21:31
For now I implemented a small proxy over the `pool.getConnection` and `connection.release` to monitor if the interval between them is more than a certain period but I'm not sure about this approach. I'm anxiously waiting for yours Doug :)

**Comment by dougwilson** [comment] 2016-06-21 21:34
Hi @dresende, as far as tracking any official feature, this is a duplicate of #1366, which will be used to track any implementation (you're welcome to make a PR to implement :) ). That issue I believe even includes a gist of a hacky way to do it right now.

I would probably do something like the following, as a hack:
```js
;(function () {
  var _getConnection = pool.getConnection;
  pool.getConnection = function (cb) {
    var trace = new Error('connection not released after 2 minutes');
    var timer = setTimeout(function () {
      console.log(trace);
    }, 60000);
    _getConnection.call(this, function (err, conn) {
      if (err) return cb(err);
      var _release = conn.release;
      conn.release = function () {
        clearTimeout(timer);
        conn.release = _release;
        conn.release();
      };
      cb(null, conn);
    });
  };
}();
```

**Comment by dougwilson** [comment] 2016-06-21 21:36
But otherwise, as for an implementation withing this library, I was thinking that we could add a pool option (and an options object to `.getConnection` for overriding) that you can specify the "maxCheckoutTime" or similar and once that elapsed, we would remove that connection from the pool and terminate it, and probably emit an error from it or something (or perhaps just emit an event from the pool saying that occurred so the user can log it somehow).

**Comment by dresende** [comment] 2016-06-21 21:36
That hack is similar to mine, but since I have an abstraction over `mysql` I hacked there and added some options like on/off and timeout time. Perhaps it's better to keep this feature off the core.

**Comment by dougwilson** [comment] 2016-06-21 21:37
#1311 also looks like a duplicate (just trying to link these all together).

**Comment by dresende** [comment] 2016-06-21 21:39
For reference, I started to notice this when upgraded the driver from mysql 2.10.1 to 2.11.1. I'm not sure if it was the upgrade or some new code in the meantime, so I'm not blaming anything for now.

**Comment by dougwilson** [comment] 2016-06-21 21:41
Yea, 2.11.0 had a lot of changes, though not pool-related off the top of my head. Unless you're using a new feature (I don't think there really was any), you can try downgrading to see if that helps at all. I'll be happy to prioritize any bug fixes, of course :)!

**Comment by dresende** [comment] 2016-06-21 21:43
I'm going to put this change in staging and check if at least I detect connections not being released. If I can consistently replicate it I'll downgrade and if that solves I'll just have to use bisect on the two versions.

**Comment by dougwilson** [comment] 2016-06-21 21:47
Awesome :) I'll keep this open while waiting to hear back :) I'll try to poke at the changes as well tonight.

**Comment by dresende** [comment] 2016-06-24 10:22
I have detected unreleased connections from pool but the fault was detected outside the lib so for now this is OK. @dougwilson you can close this if you want

**Closed** 2017-01-20 01:50 UTC
Labels: question
