### ISSUE TITLE
error /usr/bin/git ls-remote -h -t ssh://git@github.com/mysqljs/mysql.git

### ISSUE THREAD

**Issue by loretoparisi** [mysqljs/mysql#1938] opened 2018-02-13 16:57 UTC
I'm using `npm install` in a git submodule that it is using `mysql` as dependecy. When I try to run `npm install` in the submodule I get this weird error:

```
5 verbose stack Error: exited with error code: 128
15 verbose stack     at ChildProcess.onexit (/usr/local/lib/node_modules/npm/node_modules/mississippi/node_modules/end-of-stream/index.js:39:36)
15 verbose stack     at emitTwo (events.js:126:13)
15 verbose stack     at ChildProcess.emit (events.js:214:7)
15 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
16 verbose cwd /root/custom-node-sdk
17 verbose Linux 4.9.60-linuxkit-aufs
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
19 verbose node v8.9.4
20 verbose npm  v5.6.0
21 error Error while executing:
21 error /usr/bin/git ls-remote -h -t ssh://git@github.com/mysqljs/mysql.git
21 error
21 error fatal: Not a git repository: ../.git/modules/custom-node-sdk
21 error
21 error exited with error code: 128
22 verbose exit [ 1, true ]
```

My folder structure is like

```
root
|-node_modules/
|_custom-node-sdk
   |-node_modules/
```

where `custom-node-sdk` is using `mysql` as dependency.

**Comment by loretoparisi** [comment] 2018-02-13 17:26
What I have found was that I had to remove the `.git` folder from the submodule in order to make it working.

**Comment by dougwilson** [comment] 2018-02-13 17:29
Interesting. I'm not sure how to reproduce to see what we need to change. Do you have any ideas on what we need to change? Or if you're not sure, that's understandable. Can you provide instructions so I can setup a reproduction and I can see what the issue is?

**Comment by dougwilson** [comment] 2018-03-21 23:19
I'm closing since I never heard anything back.

**Closed by dougwilson** 2018-03-21 23:19 UTC
Labels: needs more info
