### ISSUE TITLE
Node hangs after finishing streaming a long query

### ISSUE THREAD

**Issue by marer** [mysqljs/mysql#1590] opened 2016-12-01 00:21 UTC
I have a problem with app execution hanging for 12 seconds after a mysql call. During that time event loop is blocked and other events (like a heartbeat) are not processed, which causes app to disconect from rabbitmq.

I'm using mysqljs/mysql to fetch records from a local mysql database, process them and save to mongo. A simplified version is pasted below. I've replaced asynchronous mongo calls with a dummy, and eventually removed it as it turned out setTimeout(() => connection.resume(), 1) reproduces the problem.

main file
```javascript
return Q()
    .then(() => mysqlq.each(query, [customer_id]))
    .tap(() => console.log('after each'))
````

mysqlq wrapper

```javascript
const connection = mysql.createConnection(settings);
this.each = (sql, values) => new Promise((resolve, reject) => {
    connection.query(sql, values)
        .on('error', reject)
        .on('result', (row) => {
            connection.pause();
            //actual processing is normally taking place here
            setTimeout(() => connection.resume(), 1);
        })
    .on('end', () => {
        console.log('on end');
        resolve();
        console.log('after resolve');
    });
});
```

For a query that returns about 130000 rows the application hangs between "after resolve" and "after each" for about 12 seconds (Shorter result sets don't have that problem). It doesn't process anything else, including heartbeats. I've even tried to send a signal to invoke a heap dump, but it's not being processed during that time.

```
[2016-11-30 17:05:30.171 UTC] [LOG] on end
[2016-11-30 17:05:30.179 UTC] [LOG] after resolve
[2016-11-30 17:05:42.281 UTC] [LOG] after each
```

The app does not hang when **setTimeout(() => connection.resume(), 1);** is replaced with synchronous **connection.resume()** call.

```
[2016-11-30 17:01:45.390 UTC] [LOG] on end
[2016-11-30 17:01:45.395 UTC] [LOG] after resolve
[2016-11-30 17:01:45.395 UTC] [LOG] after each
```

Heap size looks stable. GC tracking does not show any runs after "on end". Profiling showed that during hang time _ZN2v88internal4Heap12MoveElementsEPNS0_10FixedArrayEiii was being executed (link to flame chart below).

Does anyone know what might be causing the problem?

I'm using:
Docker: 1.12.3
Ubuntu: 14.04.5 LTS
node: v6.9.1
mysql server: 5.5.49
mysqljs/mysql: 2.11.1

**Comment by dougwilson** [comment] 2016-12-01 05:11
Can you share what is in `//actual processing is normally taking place here` comment above? If not, and your run the code as-is where you do no processing at all like the above, does it still have the issue?

**Comment by marer** [comment] 2016-12-01 09:59
With no processing (as in code above) the app still has this issue. When I replace `setTimeout(() => connection.resume(), 1);` with `connection.resume()` the issue disappears.

**Comment by marer** [comment] 2016-12-01 14:33
Looks like this call is lagging: 

```
Stacktrace from V8 profiling
	at  (/usr/local/bin/node)
	at  (/usr/local/bin/node)
	at _combineNextBuffers (/app/shared/npm/node_modules/mysql/lib/protocol/Parser.js:383:68)
	at write (/app/shared/npm/node_modules/mysql/lib/protocol/Parser.js:25:40)
	at _tickCallback (internal/process/next_tick.js:87:25)
```

Proof: http://i.imgur.com/O8XLprw.png

**Comment by dougwilson** [comment] 2017-01-14 05:38
Is there anyway you can get what those two functions that are active in Node.js core at the top of the trace are?

**Comment by dougwilson** [comment] 2017-01-20 06:41
Hi @marer without additional information, I really can't do anything other than take random stabs in the dark to see if maybe your issue is fixed, since there isn't enough information here for me to reproduce the issue.

I did just make some improvements around the area in our code where your stack trace above show (but I really need to know those top to Node.js functions to determine where in the other function it's spending it's time), so if you could at least try to install this branch to see if it makes any difference.

For now you'll need to be my eyes / ears while I bounce different trials so you can see if it makes a difference or not :)

Instructions to install:
```
$ cd into/your/project
$ npm cache clean
$ npm install mysqljs/mysql#buflist
```

**Comment by marer** [comment] 2017-01-20 08:27
Hey... I'll check today if the issue was fixed. If not I'll try to make an app that reproduces the error over the weekend or on Monday. Thanks for your time.

**Comment by marer** [comment] 2017-01-20 15:35
I've checked my app with the latest version from master, and the problem haven't been solved.

**Comment by dougwilson** [comment] 2017-01-20 15:37
I didn't put anything for this on master :) it is on another branch. Did you use the install instructions I posted above?

**Comment by dougwilson** [comment] 2017-01-20 17:17
Hi @marer did you have the chance to try the correct branch yet?

**Comment by dougwilson** [comment] 2017-01-21 01:16
So I've been playing around trying to make a script based on what you had above to see if I can reproduce. I may be reproducing, but not sure quite yet.

**Comment by dougwilson** [comment] 2017-01-21 01:36
Great news, I made a script that did what yours did, and make a temp table and filled it with 130,000 random rows. When I ran with the `setTimeout`, it would hang at the end for 10 seconds, but without that, it would not hang at all. The changes on the `buflist` branch did indeed fix the issue 💃 I'm going to merge it into `master` and close this issue. I'm going to leave that branch there for a while so you can follow my install instructions above to confirm as well, but as best as I can tell it is resolved.

**Comment by dougwilson** [comment] 2017-01-21 01:37
For reference, here is the script I was using:
```js
var crypto = require('crypto');
var mysql = require('./index');

var ROW_COUNT = 130000;

var connection = mysql.createConnection({
        host: process.env.MYSQL_HOST,
        user: process.env.MYSQL_USER,
        database: process.env.MYSQL_DATABASE
});

connection.query('CREATE TEMPORARY TABLE large_test (id INT NOT NULL AUTO_INCREMENT, random VARCHAR(20) NOT NULL, PRIMARY KEY (id))');

function insertAll(callback) {
        var count = ROW_COUNT;

        function next() {
                var size = Math.min(count, 1000);
                if (!size) return callback();
                count -= size;
                insertBatch(size, next);
        }

        next();
}

function insertBatch(count, callback) {
        var rows = [];

        for (var i = 0; i < count; i++) {
                rows.push([crypto.randomBytes(10).toString('hex')]);
        }

        connection.query('INSERT INTO large_test (random) VALUES ?', [rows], callback);
}

insertAll(function () {
        var i = 0;
        connection.query('SELECT * FROM large_test')
        .on('result', function () {
                connection.pause();
                if (++i % 1000) {
                        setTimeout(function () {
                                connection.resume();
                        }, 1);
                } else {
                        connection.resume();
                }
        })
        .on('end', function () {
                console.time('end');
                connection.end(function () {
                        console.timeEnd('end');
                });
        });
});
```

**Comment by dougwilson** [comment] 2017-01-21 01:47
And in fact, the changes on the `buflist` branch may have solved it, not they actually solved it on accident :) I'm going to make a commit to specifically fix this issue on purpose before moving those commits, since technically the issue may still exist. Essentially the issue is that every call to `.resume()` will schedule an internal `.write()` call for later. All those write calls eventually fill up an internal array with empty values and at the end, the `_combineNextBuffers` method ends up walking and `.shift()`ing through tens of thousands of values, which is where the time gets consumed.

**Closed** 2017-01-21 02:22 UTC
Labels: bug

**Comment by marer** [comment] 2017-01-21 07:57
It's great to hear that the issue was solved. Sorry for not being very helpful, but it has been a busy week for me. Thanks :)

**Comment by marer** [comment] 2017-01-23 09:52
Hey... could you tag a new release with the fix so we could use it in a civilized manner? Thanks :)

**Comment by dougwilson** [comment] 2017-01-23 11:54
I was waiting for you to confirm the fix, which is why I left the branch. Does this mean you have confirmed your issue is fixed?

**Comment by marer** [comment] 2017-01-23 12:59
Confirmed. It's fixed :)

**Comment by dougwilson** [comment] 2017-01-23 13:14
Awesome! I was hoping to hear back from another user who also had no information on how I could reproduce their issue and took a stab at it. If I don't hear back in 10 hours or so I'll release anyway (but also, I need to finish traveling on planes today to release anyway).
