### ISSUE TITLE
Need support for caching_sha2_password authentication

### ISSUE THREAD

**Issue by robwhess** [mysqljs/mysql#2005] opened 2018-05-01 23:34 UTC
MySQL uses the `caching_sha2_password` authentication plugin by default in version 8.0:

https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html

Trying to use the `mysql` package to query against a server using this authentication plugin results in the following error:
```
{
  code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
  sqlState: '08004',
  fatal: true,
  ...
}
```

With MySQL version 8.0 recently released for general availability, it would be nice to be able to use the `mysql` package to run queries against a MySQL 8.0 server without messing with the server's configuration.

This issue stems from my comment on #1507.  I apologize for posting there in the wrong thread.  I don't have the time or understanding of this package or the internals of MySQL to submit a PR for this myself, but I wanted to bring it to the attention of the maintainers, since it may become a pressing issue as more people start to use MySQL 8.0.

**Comment by dougwilson** [comment] 2018-05-02 00:00
It's no problem. I also apologize for then going and closing your issue here, but just trying to clean up. I believe this is a duplicate of https://github.com/mysqljs/mysql/issues/2002

Please let me know if it's not a duplicate, though, and I can reopen. I may need more information though to understand what isn't a duplicate to better assist :+1:

**Closed by dougwilson** 2018-05-02 00:00 UTC

**Comment by hackdavid** [comment] 2020-05-30 05:40
if you are facing "caching_sha2_password" error during connectivity of your mysql database using python ,
go through this
https://www.youtube.com/watch?v=YNq-EuQEJos
