### ISSUE TITLE
Using pool without destroying connection makes system to hang

### ISSUE THREAD

**Issue by bfanyuk** [mysqljs/mysql#1775] opened 2017-07-19 19:17 UTC
```
var settings = require('./settings');
var mysql = require('mysql');
var pool = mysql.createPool({
    host: settings.host,
    database: settings.database,
    user: settings.user,
    password: settings.password
});
pool.query('select 1', null, function (error, result) {
    console.log(result);
});
```

This code prints result but never ends. 
If I deploy this code to Amazon Lambda - endpoint finishes with timeout error.

If I add **connection.destroy** - this code finishes successfully:
```
pool.getConnection(function (error, connection) {
    connection.query('select 1', null, function (error, result) {
        connection.destroy();
        console.log(result);
    });
});
```

But I suppose destroying connection is not a good practice.
If I use **connection.release()** instead of **connection.destroy** - this doesn't help, hangs as in first example.

**Comment by dougwilson** [comment] 2017-07-19 19:19
Node.js will hang open in your example because there is still an active network connection. You just need to use `poo.end` to close the pool when you want everything to shutdown: https://github.com/mysqljs/mysql#closing-all-the-connections-in-a-pool

**Closed by dougwilson** 2017-07-19 19:19 UTC

**Comment by bfanyuk** [comment] 2017-07-20 08:44
@dougwilson This solution is OK for this one-time command line program.
But how can I close the pool when I have some server that should serve requests for indefinite time?
In my case I am using Amazon Lambda + API Gateway.
Request fails with timeout error if I don't destroy all connections.

**Comment by dougwilson** [comment] 2017-07-21 00:02
Hi @bfanyuk the purpose of the pool is that the connections do not close, and remain open between use. If leaving them open doesn't work for your use-case, then you would need to create a brand new connection each time.

I am not familiar with Lambda, so have no specific information regarding the use on Lambda. The reason I suggested pool.end is because that is the solution for the reproduction case you provided. It may not be the issue in Lambda, I just have no idea how Lamba works.

**Comment by ayankousky** [comment] 2017-10-19 11:13
@bfanyuk , you can try _context.callbackWaitsForEmptyEventLoop = false;_ [http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html](url). 

Worked for me. But I didn't test it on a huge amount of requests (don't understand how this "freeze" behavior works on connections). I will do it later and put the results here when I finish

**Comment by bfanyuk** [comment] 2017-10-19 11:42
Thanks, @ayankousky !
Yes, since I posted this issue I found the solution you proposed and actively use it.
