### ISSUE TITLE
Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by IonutAlexandruPanait** [mysqljs/mysql#1854] opened 2017-10-27 07:51 UTC
Connection lost: The server closed the connection.
    at Protocol.end (/home/ec2-user/AIP/node_modules/mysql/lib/protocol/Protocol.js:113:13)
    at Socket.<anonymous> (/home/ec2-user/AIP/node_modules/mysql/lib/Connection.js:109:28)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)

**Comment by dougwilson** [comment] 2017-10-27 14:51
Hi @IonutAlexandruPanait the message states that the server closed the connection. There isn't enough information to diagnose further.

**Comment by zenmanenergy** [comment] 2017-10-28 12:26
This just recently happened to me, after a bit of research I think using pooled connections and releasing the connection back to the pool is the answer. Like this:

```pool.getConnection(function(err, connection) {
  // Use the connection
  connection.query('SELECT something FROM sometable', function (error, results, fields) {
    // And done with the connection.
    connection.release();

    // Handle error after the release.
    if (error) throw error;

    // Don't use the connection here, it has been returned to the pool.
  });
});

**Comment by IonutAlexandruPanait** [comment] 2017-10-29 09:45
@dougwilson I can't understand why the server closed the connection but I did try to use @zenmanenergy solution and now I get a new error: TypeError: dataBase.release is not a function

**Comment by zenmanenergy** [comment] 2017-10-29 15:15
Oh. my copy/paste didn't work... try this:

```
var mysql = require('mysql');
var pool  = mysql.createPool({
  host     : 'example.org',
  user     : 'bob',
  password : 'secret',
  database : 'my_db'
});

pool.getConnection(function(err, connection) {
  // Use the connection
  connection.query('SELECT something FROM sometable', function (error, results, fields) {
    // And done with the connection.
    connection.release();

    // Handle error after the release.
    if (error) throw error;

    // Don't use the connection here, it has been returned to the pool.
  });
});
```

**Comment by IonutAlexandruPanait** [comment] 2017-10-29 15:44
@zenmanenergy Thank you so much! I don't think I really understand what a pool is.. Do you have any idea if is possible to export this pool connection? As I did in the following code with database connection? Or I should make a pool for every query?

I found I had 9 connections to database because I exported connection function and call it instead export connection result and call it. Now I have only one connection and I have to wait 24h to see if I still have the same problem with "The server closed the connection." If the problem will still exist after that I will put in production pool connection.

```
var mysql = require('mysql');
var pool  = dataBase.createConnection({
  host     : 'example.org',
  user     : 'bob',
  password : 'secret',
  database : 'my_db'
});


dataBase.connect();
handleDisconnect(dataBase);

function handleDisconnect(client) {
	client.on('error', function (error) {
	    if (!error.fatal) return;
	    if (error.code !== 'PROTOCOL_CONNECTION_LOST') throw err;

	    console.error('> Re-connecting lost MySQL connection: ' + error.stack);

	    // NOTE: This assignment is to a variable from an outer scope; this is extremely important
	    // If this said `client =` it wouldn't do what you want. The assignment here is implicitly changed
	    // to `global.mysqlClient =` in node.
	    mysqlClient = mysql.createConnection(client.config);
	    handleDisconnect(mysqlClient);
	    mysqlClient.connect();
	});
};

exports.connectToDataBase = function() {

    return dataBase;

};
```

**Comment by IonutAlexandruPanait** [comment] 2017-10-30 20:04
@zenmanenergy And I also think it is not ok to use pool when you have a lot of connections.

**Comment by dougwilson** [comment] 2017-12-15 19:17
I'm going to close this because there is still not enough information. Without instructions on how to reproduce the issue I'm not able to answer why your connection was closed, unfortunately.

**Closed by dougwilson** 2017-12-15 19:17 UTC
Labels: needs more info

**Comment by shohelk** [comment] 2018-05-25 13:08
Got the same problem when I forgot to do: **npm install**

May help someone with the same issue
