### ISSUE TITLE
Replace rowdatapacket object with array

### ISSUE THREAD

**Issue by HaoyangFan96** [mysqljs/mysql#2065] opened 2018-07-10 18:24 UTC
I am wondering if there is a option that can change the format of results from a rowdatapacket to array

For example,
instead of 
`[rowdatapacket {"colA": "valA", "colB": "valB,  "colC": "valC,  "colD": "valD"}, ...]`
I just want the values of the columns, and I don't really need the repeated column names again and again, so a array that contains all row values is the best 
`[["valA", "valB", "valC", "valD"], ...`

Currently what I can do is a very naive approach: in the callback `(err, results, fields)`, I convert each rowdatapacket object to array row by row, which I thought will be very inefficient

Fon similar question and feature request: #770 #1633 

Thanks

**Comment by dougwilson** [comment] 2018-07-10 18:32
Yea, it's not possible yet, which is why those are still open :(

Duplicate of #770

**Closed by dougwilson** 2018-07-10 18:32 UTC
