### ISSUE TITLE
Authorization Issue fixed yet?

### ISSUE THREAD

**Issue by christian-hess-94** [mysqljs/mysql#2172] opened 2019-01-31 17:29 UTC
I'm getting the famed ER_NOT_SUPPORTED_AUTH_MODE issue when installing mysql community server 8.0
I am scouring the internet for a solution and all I get are posts from 2018 saying that it isn't supported by the module.
Is the new authentication method now supported? If yes, can someone link me how to make this connection possible? 
I am talking about the caching_sha2_password plugin that was the rage sometime ago.
Current code (using TypeScript) is:

```
import mysql from 'mysql';

let connection = mysql.createConnection({
        host: 'localhost',
        port: 3306,
        user: 'root',
        password: 'Sistemas!@#',
        database: 'db_app'
    })
```

**Comment by dougwilson** [comment] 2019-01-31 17:33
duplicate of #2002 , which contains a work-around as well in that thread.

**Closed by dougwilson** 2019-01-31 17:33 UTC
Labels: duplicate

**Comment by dougwilson** [comment] 2019-01-31 17:34
My apologies, the work-around is in the pull request to implement the 8.0 auth method: https://github.com/mysqljs/mysql/pull/1962#issuecomment-390900841

**Comment by christian-hess-94** [comment] 2019-01-31 17:46
Ok but that does not answer my question. Like I said I'm aware that there are work arounds to this issue. The thing is I am asking if there is a way to use this library with caching_sha2_password , not native_password. I am aware that there are work arounds to this by changing or creating new users that use the old authentication method.

**Comment by christian-hess-94** [comment] 2019-01-31 17:47
I'm sorry but I find it a bit hard to believe that #1962, which was opened almost a year ago, still hasn't been resolved so I need the confirmation if it was but the thread simply wasn't updated or if this is still a pressing matter.

**Comment by dougwilson** [comment] 2019-01-31 17:47
Does the answer at the bottom of #2002 not answer the question? Not sure how to really word it better.

**Comment by dougwilson** [comment] 2019-01-31 17:49
PR #1962 has merge conflicts and doesn't pass the existing tests. Someone needs to fix it up. The author has not yet and I haven't gotten around to it, but anyone can and open a PR with a working changeset that I can actually merge and release.

**Comment by christian-hess-94** [comment] 2019-01-31 17:53
Hadn't seen the bottomest comment. One last question then: where would be the best thread to subscribe to so that I can know when a release that addresses the issue is posted?

**Comment by dougwilson** [comment] 2019-01-31 17:55
Just click on subscribe on the left-hand side on #2002 . I will post a comment in addition to closing it because I know there are people sub'd to it. I am just trying to come back to work on this from the back log of work I have to do at work after being off for the holidays. I just only have so much time to get things done and I just volunteer here without pay :) The harsh winter this year is not helping as a lot of my free time is eaten into by the extra time it takes just to commute and stuff :(

**Comment by dougwilson** [comment] 2019-01-31 18:04
Awesome. I do this because I do like to do this kind of stuff and so I personally look forward to working on this, and would very much love to see it land just as much as you and many others. The auth was overhauled in 8.0, which resulted in a lot of under the hood changes to this module to support it, which makes it a bit more intense than a lot of the others. But challenges are fun at the same time.

**Comment by christian-hess-94** [comment] 2019-01-31 18:06
Agreed. Well I will start to reimplement the native_password module then and wait for the new update. Good luck man look forward to speaking to you sometime in the future :)
