### ISSUE TITLE
connection.threadId undefeind

### ISSUE THREAD

**Issue by sayeko** [mysqljs/mysql#2027] opened 2018-05-26 00:09 UTC
I'm getting in the connection.threadId proeprty always undefined from some reason.

**Comment by dougwilson** [comment] 2018-05-26 00:14
Very strange. What version of this module are you using? Version if Mysql server? And code to reproduce? We can take a look :+1:

**Comment by sayeko** [comment] 2018-05-26 00:31
Node 8+
"mysql": "^2.15.0"
Mysql server 5.7.11

Code:
	onAcquire(connection) {
		debug(`Connection ${connection.threadId} acquired`);
	}
	onRelease(connection) {
		debug(`Connection ${connection.threadId} released`);
	}

**Comment by dougwilson** [comment] 2018-05-26 00:45
So I setup those versions and it is working for me just fine. I also logged it before connecting and it will output null instead of undefined so I have no idea how you're getting underfunded. Is it possible you can provide complete source code I can run without modification? Your code was unrunnable by itself so I had to make significant modifications and not sure if that's why it's working for me.

**Comment by sayeko** [comment] 2018-05-26 00:58
```
this.pool = mysql.createPool(configuration);

this.subscribePoolEvent(this.pool, 'connection', this.onConnection);
this.subscribePoolEvent(this.pool, 'enqueue', this.onEnqueue);
this.subscribePoolEvent(this.pool, 'release', this.onRelease);
[this.subscribePoolEvent(this.pool,](url) 'acquire', this.onAcquire);

subscribePoolEvent(pool, eventName, handler) {
  pool.on(eventName, () => {
  handler.apply(this, arguments);
  });
}

[https://user-images.githubusercontent.com/23419176/40570941-f21e78e8-6098-11e8-97ad-a001877bd44d.JPG](url)

```

**Comment by sayeko** [comment] 2018-06-08 08:39
Provided full info

**Comment by dougwilson** [comment] 2018-07-27 22:31
Hi @sayeko I'm still unable to reproduce or run the code you're prividing without any modifications. Please provide code I can copy and paste and run without modification to reproduce. Likely the modifications I need to make just to get the code to run is why I'm unable to reproduce.

**Comment by kai-koch** [comment] 2018-11-09 11:03
Please provide more info and working example code, so we can try to help you.

Closing for now. You can reopen with more info.

**Closed by kai-koch** 2018-11-09 11:03 UTC
Labels: needs more info
