### ISSUE TITLE
Timeout on Electron refresh (CTRL + F5)

### ISSUE THREAD

**Issue by jenstornell** [mysqljs/mysql#2370] opened 2020-06-30 09:08 UTC
I use Electron and mysql. When I start the application it works fine.

If I refresh with CTRL + F5 the browser window reloads. Then everything works as before but not mysql.

I get this message:

>Error: connect ETIMEDOUT

```js
let connection = mysql.createConnection(params);
connection.connect();
connection.query("SELECT * FROM my_table",
  (error, results) => {
    if (error) {
     console.log(error);
    } else {
     console.log(results);
    }
  }
);
```

1. Everything works fine when starting the Electron app.
2. Connection timeout when refresh the browser with CTRL + F5 and try again
3. My params are still there in both cases.

How can I solve this?

![infinity](https://user-images.githubusercontent.com/927011/86109026-36903c00-bac4-11ea-8aa0-801d91f782f5.gif)

**Comment by neosix** [comment] 2020-10-08 10:07
I have the same issue. @jenstornell  did you find solution?

**Comment by jenstornell** [comment] 2020-10-08 13:26
@neosix No. I tried it out again yesterday without luck.

I think someone that has the time need to make a really small project just to isolate this issue.

**Comment by dougwilson** [comment] 2022-03-13 20:06
I'm going to close this issue since no reproduction has surfaced in order to debug. You're welcome to either provide one for us to investigate or pull request a fix.

**Closed by dougwilson** 2022-03-13 20:06 UTC
Labels: needs more info
