### ISSUE TITLE
How to request ssl use the default trust store, rather than specify the CA?

### ISSUE THREAD

**Issue by menicosia** [mysqljs/mysql#1848] opened 2017-10-21 04:06 UTC
Sorry if this documented, I haven't been able to find an answer.

Right now, the docs specify that the minimum required to use an SSL/TLS connection while validating the server's certificate is:

```js
var connection = mysql.createConnection({
  host : 'localhost',
  ssl  : {
    ca : fs.readFileSync(__dirname + '/mysql-ca.crt')
  }
});
```

However, I believe that if the server's certs are signed by a CA that is also in the systems trust store, supplying the CA should not be necessary. See https://github.com/nodejs/node/issues/4175#issuecomment-243715727

Is there a way to be lazy and not re-specify the CA? Something like:

```js
var connection = mysql.createConnection({
  host : 'localhost',
  ssl  : {}
});
```

... would be ideal.

**Comment by dougwilson** [comment] 2017-10-21 04:13
It's not documented well, but it is the last example in the section https://github.com/mysqljs/mysql/blob/master/Readme.md#ssl-options

**Comment by menicosia** [comment] 2017-10-21 04:57
Hi @dougwilson thanks for your response. I'm not sure I understand. Are you suggesting I specify `rejectUnauthorized: true`?

**Comment by dougwilson** [comment] 2017-10-21 04:58
Hi @menicosia I'm not sure what you mean. The last example has `rejectUnauthorized: false`. Are you seeing something different?

**Comment by dougwilson** [comment] 2017-10-21 05:00
Here is the example I am referring to:
```js
var connection = mysql.createConnection({
  host : 'localhost',
  ssl  : {
    rejectUnauthorized: false
  }
});
```

**Comment by dougwilson** [comment] 2017-10-21 05:02
Oh, I just realized what that means. The double-negative is really throwing me off. Yea, I believe you can use an empty object like your OP: `ssl: {}` to just use the Node.js CA logic. Does that not work?

**Comment by menicosia** [comment] 2017-10-21 16:42
Afraid not. Neither `ssl: {}` nor `ssl: {rejectUnauthorized: true}` work. I delayed responding till I made sure I was using a recent version - I'm testing on `node 8.6.0`.

**Comment by dougwilson** [comment] 2017-10-21 16:56
Interesting. In the meantime I tested against Azure which uses certs that are part of Node.js (they use public domain certs) and using {} worked fine. If you can hrlp me replicate the issue I can debug through where the issue is, or if you can PR a fix. If you want me to take a look, I'll need the following:

1. Version of this module 
2. Version of MySQL server
3. Complete code you are trying to use
4. Complete instructions for how you have setup the SSL on the server (or a way for me to connect to a server you have setup).

Thanks!

**Comment by dougwilson** [comment] 2017-10-21 16:59
For the error (which wasn't in the original email) the HANDSHAKE_SSL_ERROR is just the code. If you can provide the message property and stack trace that may help shed light on this as well.

**Comment by dougwilson** [comment] 2017-10-21 17:05
I will also check on 8.6.0 as well, since I tested on 6.11.4 while you gater the additional information.

**Comment by menicosia** [comment] 2017-10-21 17:35
@dougwilson thank you much for being super responsive and testing against a known implementation like Azure.

This leads me to worry that perhaps the CA certs that are expected to be in my trust store... are not actually in my trust store. (My project is a PaaS that is supposed to take care of automate distribution of certs, Cloud Foundry.)

Please put this bug on hold while I escalate internally.

**Comment by dougwilson** [comment] 2017-10-21 17:42
Also, I'm not sure if you know (but I just realized from your notes) that if the CA you need is not part of the static set built into Node.js directly, then unless you have manually compiled Node.js yourself with the compile time flag to have it use the OpenSSL system store, your CA is probably not visible to Node.js (if you are getting a bin built by a distro they may have it setup for you). There is also the environment variable NODE_EXTRA_CA_CERTS will look at to load in extra CAs as well.

If you suspect it is a CA issue, there is probably some Node.js API to get the list of all CAs your Node.js knows about and you can verify if it is indeed in the list or not.

**Comment by menicosia** [comment] 2017-10-21 17:51
Thanks, I've added this to our [issue #152172167](https://www.pivotaltracker.com/story/show/152172167). I'll check back!

**Comment by dougwilson** [comment] 2017-10-21 17:55
Awesome :) I'm happy to help figure out what the caude is if needed. I'll likely follow this up to allow just "ssl: true" as a shortcut as well.

**Comment by dougwilson** [comment] 2022-03-14 00:13
Hi @KuSh I went to add `ssl: true` support, and come to my surprise: it does work! Unfortunately it does not work the same as `ssl: {}`, in that `rejectUnauthorized` defaults to `false` instead of `true`... since there are things documenting that it does indeed work, it is unlikely I can fix it without a major release, as it would break a lot of folks, as internal MySQL instances are very likely use to use certs from the public PKI.

**Comment by dougwilson** [comment] 2022-03-14 00:16
I'm going to close this as the original OP has the answer from so long ago for how to use the default Node.js store.

**Closed by dougwilson** 2022-03-14 00:16 UTC
Labels: question
