### ISSUE TITLE
Getting “server closed the connection” error for mysql module from node.js

### ISSUE THREAD

**Issue by johnysv** [mysqljs/mysql#2199] opened 2019-03-20 08:17 UTC
I am trying to query a table from node.js. Below is my code.But I get the error like "server closed the connection". Not sure what blunder mistake I am doing.

```js
var mysql = require('mysql');

var con = mysql.createConnection({
  host: "10.90.103.4",
  user: "someuser",
  password: "********",
  database: "db",
  port: 1521
});

console.log("---------------------------");
console.log(con);
console.log("---------------------------");


con.connect(function(err) {
  if (err) throw err;
  con.query("select * from CLE_EXCEPTIONRECORD where CORRELATIONID='983b2f58-e0eb-49cb-b76c-9b8107de3edc'", function (err, result, fields) {
    if (err) throw err;
    console.log(result);
  });
});
```

Note: I even created an outbound rule for my db port 1521 in firewall

**Comment by johnysv** [comment] 2019-03-21 13:47
@dougwilson

**Comment by dougwilson** [comment] 2019-03-21 13:54
Would need a pcap (packet capture) of the event to verify if the issue is with this module or not

**Comment by marcus-hiles** [comment] 2019-03-22 11:06
Hi @johnysv checkout this closed issue https://github.com/mysqljs/mysql/issues/897 . It might help.

**Comment by johnysv** [comment] 2019-03-22 11:27
@marcus-hiles I have tried pool too. But the same error. @dougwilson Can you please let me know how to get pcap for this?

**Comment by dougwilson** [comment] 2019-03-22 12:48
What operating system is the node js module running on?

**Comment by johnysv** [comment] 2019-03-22 12:50
OS- windows 64bit

**Comment by dougwilson** [comment] 2019-03-22 13:52
For Windows, probably the easiest will be to use Wireshark (https://www.wireshark.org/). And here is a link to the user guide section for performing captures: https://www.wireshark.org/docs/wsug_html_chunked/ChapterCapture.html

The idea is to get a capture o the TCP packets between your client and your MySQL server, in order to determine why this module is saying the server closed the connection in your example. It could just be because the server did, in fact, close the connection, in which case this library reported it correctly, but if not, I can see what mistake is happening.

**Comment by johnysv** [comment] 2019-03-25 12:51
Hi I have tried capturing. But not sure If I m correct.Also attached the file herewith.
[test.zip](https://github.com/mysqljs/mysql/files/3003283/test.zip)

Please see the below screen shot which is how I captured. In case if u need to do anything let me know.

![image](https://user-images.githubusercontent.com/41629868/54920902-5b2e5900-4efc-11e9-9656-644fbf9698e0.png)

Below are the options I got and I selected "ethernet 2" for the packets attached.

![image](https://user-images.githubusercontent.com/41629868/54921078-bfe9b380-4efc-11e9-9751-d7b33cdc0042.png)

**Comment by johnysv** [comment] 2019-03-26 13:54
will node versio (old version) affect mysql module? @dougwilson

**Comment by marcus-hiles** [comment] 2019-03-27 10:28
> @marcus-hiles I have tried pool too. But the same error. @dougwilson Can you please let me know how to get pcap for this?

oh ok, cool

**Comment by johnysv** [comment] 2019-04-04 10:29
please anyone help me with this

**Comment by dougwilson** [comment] 2019-04-04 15:04
Hi @johnysv sorry I have been away and just got back last night. I just pulled up your capture file and I can't find the packets for MySQL in there. I looked at the packets related to 10.90.103.4 assuming that is the IP based on your original post, but that just shows opening TCP connection at time 4 and then nothing happening and the server side closing down the TCP connection at time 64.

Is that an accurate description of what you're seeing in the capture as well?

The MySQL server protocol is a "server talks first" protocol. Based on this capture, even though Node.js opened the TCP port to port 1521 server 10.90.103.4, the server never sent any data back, then simply closed the connection 60 seconds later.

As far as I can tell, there is nothing this module can do in the case you're showing; until data is sent from the MySQL server over that open TCP connection, this module cannot send the handshake data, since part of that data is based on what the server sends back.

The error you're getting is accurate based on the packet capture -- the server is closing the connection.

Why your MySQL server is not sending any data is unfortunately beyond me. Perhaps there is still a firewall rule somewhere, or perhaps that is not the right IP or port. Are you able to connect with any other MySQL client software from the same machine to that MySQL server?

**Comment by johnysv** [comment] 2019-04-06 07:17
Yes from the same machime , I was able to connect and query from sql developer and also putty.
![image](https://user-images.githubusercontent.com/41629868/55666271-edf3bf80-583b-11e9-8c55-bc5df254bd58.png)

**Comment by dougwilson** [comment] 2019-04-06 14:51
Are you sure that is a Mysql server you are connecting to? What is the server version?

I ask because i see a colum of type "VARCHAR2" in your screenshot, but there is no such thing in Mysql.

**Comment by johnysv** [comment] 2019-04-09 07:50
Hi,

I am very sorry. There was a little confusion here and what we use is not mysql but oracledb. Can you please let me know how to connect oracledb from node.js

**Comment by dougwilson** [comment] 2019-04-09 12:21
Ah. You'll need to find a module that can do that. I just help maintain this module for mysql; I'm not involved with any module for oracle connection and haven't used one, so don't know one to name, sorry

**Closed by dougwilson** 2019-04-09 12:21 UTC
Labels: needs more info
