### ISSUE TITLE
(node:1116) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.

### ISSUE THREAD

**Issue by oeliok** [mysqljs/mysql#2024] opened 2018-05-23 01:12 UTC
when i use node with version > 9,then they will give the warnning.
(node:1116) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.

**Comment by prilosac** [comment] 2018-06-15 14:09
This was marked as a duplicate of #2003 but that is wrong. #2003 talks about DEP0096, this is DEP0095. I assume that they would have similar resolutions if writing the code yourself, but in this case, its the mysql plugin that's doing this, not anything in my own code, and I would like an answer for this

**Comment by dougwilson** [comment] 2018-06-15 14:13
Sorry, I didn't notice the difference in numbers. Reopening and pull request is always welcome. Since I though this was a duplicate on accident (thanks for assuming I wad being malicious instead of trying to consider that I didn't notice they were not the same) I have done no work on this. Please conduct yourself better in the future.

**Comment by prilosac** [comment] 2018-06-15 14:15
I was not intending to be malicious and I apologize that I came off that way. I will look into the code and see if I can find a fix, and will be try to come off better in the future, thanks for reopening!

**Closed** 2018-06-21 21:28 UTC

**Comment by ximendatie** [comment] 2019-03-27 05:56
I solved that
`npm install mysql`
above works well，when mysql is @2.16.0

**Comment by Codedecks** [comment] 2019-10-11 00:01
I can confirm that running "npm install mysql" solved the issue for me too. Thanks, ximendatie!
