### ISSUE TITLE
How to get affectedRows on a REPLACE INTO query?

### ISSUE THREAD

**Issue by alexbfree** [mysqljs/mysql#1759] opened 2017-06-23 11:47 UTC
I don't seem to be getting `affectedRows` back from a REPLACE INTO query?
I did read #363 which advises this is possible for INSERT, DELETE, UPDATE queries - is it not supported for REPLACE INTO? If not, is there any chance of it being supported?

**Comment by dougwilson** [comment] 2017-06-23 16:05
Hi @alexbfree those values are just read straight from the packets sent from the MySQL server. If the MySQL server it not giving the values you expect, I'm not sure what we can do, since that's all this module has to work with. Any suggestions?

**Comment by alexbfree** [comment] 2017-06-23 16:49
That's strange. I see the value as present, but undefined. What you say makes sense, unless the value is somehow being badly parsed/encoded, but I guess that is unlikely.

I think the server is returning it, since it works in other languages. I will post back here if I can narrow down the circumstances or provide more info.

**Comment by dougwilson** [comment] 2017-06-23 16:52
> unless the value is somehow being badly parsed/encoded

Yea, that's always possible. Getting a packet capture to look at would be amazing and would instantly identify the issue, but if that's not possible, provided full DDL, queries, code, and versions of things you are using so I can reproduce would help me debug the issue and track it down.

**Comment by dougwilson** [comment] 2017-07-26 00:37
Closing since I never heard back.

**Closed by dougwilson** 2017-07-26 00:37 UTC
Labels: needs more info
