### ISSUE TITLE
Lost Connection Error in Nginx + NodeJS environment

### ISSUE THREAD

**Issue by Miroku87** [mysqljs/mysql#1879] opened 2017-11-21 13:41 UTC
Hi guys,
I know this issue has come up a lot of times on this repository, but I think I have a new situation on which it occurs.
I am running my NodeJS Express application under Nginx proxy in a way that I can map my port 80 on multiple internal ports.
My application also uses [socket.io](https://socket.io/) to communicate with the client. As said [here](https://www.nginx.com/blog/websocket-nginx/), in order to use websockets under Nginx, you have to set these headers in your configurations:

```
location /app/ {
    ....
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

The problem is that, as soon as you configure these headers and then restart the service, MySQL Connections start to drop and to make the app crash.
What do you think is the relation between these Nginx Header settings and the MySQL connection life span?

Thank you in advance!

**Comment by dougwilson** [comment] 2017-12-07 15:46
I don't think they have relation, but not sure, never heard of this before. If you can help provide the instructions to get the same environment setup you have on my end, I'll have something to poke at to dig in, but don't really have enough information to begin to setup a reproduction of your issue yet.

**Comment by dougwilson** [comment] 2017-12-28 21:10
Closing since I never heard back.

**Closed by dougwilson** 2017-12-28 21:10 UTC
Labels: needs more info
