### ISSUE TITLE
ROW_COUNT() return not correct data - Critical!

### ISSUE THREAD

**Issue by tapin13** [mysqljs/mysql#1436] opened 2016-06-05 11:01 UTC
I want to return number of affected rows from Stored Procedure (SP). But always i got the same number of affected rows, but this rows was not affected (for sure!).
If I run the same SP from SqlYog or native from console, i got correct result.

SP:
```sql
DELIMITER $$

DROP PROCEDURE IF EXISTS `spUpdateCustomerField`$$

CREATE DEFINER=`root`@`%` PROCEDURE `spUpdateCustomerField`(
    `customerid` INT
    , `field` VARCHAR (1024)
    , `value` TEXT
)
BEGIN
	SET @query = CONCAT('UPDATE tcustomers SET ', `field`, ' = ? WHERE tcustomers.`fID` = ?');
	
	SET @fieldValue = `value`;
	SET @customerid = `customerid`;
	
    PREPARE stmt FROM @query;
    EXECUTE stmt USING  @fieldValue, @customerid;   

	SELECT ROW_COUNT() `affectedRows`;
    
	DEALLOCATE PREPARE stmt;
END$$

DELIMITER ;
```
Runs from console:
```
mysql> CALL spUpdateCustomerField('13', 'fDeleted', '0');
+--------------+
| affectedRows |
+--------------+
|            0 |
+--------------+
1 row in set (0.00 sec)

Query OK, 0 rows affected (0.01 sec)

mysql> CALL spUpdateCustomerField('13', 'fDeleted', '1');
+--------------+
| affectedRows |
+--------------+
|            1 |
+--------------+
1 row in set (0.00 sec)

Query OK, 0 rows affected (0.00 sec)

mysql> CALL spUpdateCustomerField('13', 'fDeleted', '1');
+--------------+
| affectedRows |
+--------------+
|            0 |
+--------------+
1 row in set (0.01 sec)

Query OK, 0 rows affected (0.01 sec)
```
Run from nodeJS:
```js
var query = "CALL spUpdateCustomerField('13', 'fDeleted', '1');";
    mysql_connection.query(query, function(err, rows) {
        console.log(rows);
    });
```
Fun First time:
```js
[ [ { affectedRows: 1 } ],
  { fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0 } ]
```
Fun Second time:
```js
[ [ { affectedRows: 1 } ],
  { fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0 } ]
```
NodeJS: 
```
node -v  v0.10.25
npm list mysql
└── mysql@2.10.2 
uname -a
Linux ip- 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
P.S. This is not cache for sure, i add `RAND()` and i add number for return rows. I try to use out variables from SP. Nothing works :(

**Comment by dougwilson** [comment] 2016-06-05 20:30
Hm, that is weird. I'd be happy to take a look, but I cannot run your procedure, since I don't know how to create the required table and what data is in the table. Can you provide me with the following?

1. SQL to create the necessary tables to run your procedure.
2. SQL to populate the table with any necessary data to run your procedure against.
3. The version of MySQL server you are using.

Another possibility is you can use Wireshark or similar to capture the packets between this module and your server when running the queries and I can confirm if we are parsing the results from the server correctly or not.

**Comment by tapin13** [comment] 2016-06-06 07:05
1. SQL to create the necessary tables to run your procedure.
CREATE TABLE `tcustomers` (
  `fID` int(11) NOT NULL AUTO_INCREMENT,
  `fUserName` varchar(255) DEFAULT '',
  `fEmail` varchar(255) DEFAULT '',
  `fPassword` varbinary(255) NOT NULL DEFAULT '',
  `fFirstName` varchar(50) NOT NULL DEFAULT '',
  `fLastName` varchar(50) NOT NULL DEFAULT '',
  `fGender` smallint(1) NOT NULL DEFAULT '3' COMMENT '0 - male 1- female',
  `fMobile` varchar(20) NOT NULL DEFAULT '',
  `fMobileVerified` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`fID`),
) ENGINE=InnoDB AUTO_INCREMENT=1816 DEFAULT CHARSET=utf8

2. SQL to populate the table with any necessary data to run your procedure against.
Any simple data.

3. The version of MySQL server you are using.
"character_set_server"	"utf8"
"collation_server"	"utf8_general_ci"
"innodb_force_recovery"	"0"
"innodb_version"	"5.5.47"
"protocol_version"	"10"
"relay_log_recovery"	"OFF"
"rpl_recovery_rank"	"0"
"server_id"	"1"
"slave_type_conversions"	""
**"version"	"5.5.47-0ubuntu0.14.04.1-log"**
"version_comment"	"(Ubuntu)"
"version_compile_machine"	"x86_64"
"version_compile_os"	"debian-linux-gnu"

**Comment by tapin13** [comment] 2016-06-14 09:14
dougwilson - any news?

**Comment by dubanflorin** [comment] 2016-06-17 07:16
try this
`"flags":` "-FOUND_ROWS"`

**Comment by dougwilson** [comment] 2016-06-18 03:38
Hi @tapin13, I have not had any time to investigate myself, sorry! Try that suggestion by @dubanflorin and let us know how it goes.

**Comment by dougwilson** [comment] 2016-09-28 01:17
Hi @tapin13 I'm going to close this issue, because you never let us know how using that flag worked for you. If you have an answer, let us know :)

**Closed by dougwilson** 2016-09-28 01:17 UTC
