### ISSUE TITLE
Timer issue with Node js v10.5.0

### ISSUE THREAD

**Issue by TruemanWu** [mysqljs/mysql#2057] opened 2018-06-27 20:16 UTC
(node:7178) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead;
(node:7178) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.

**Comment by dougwilson** [comment] 2018-06-27 20:20
Thanks for the report! We just recently fixed this on master and testing for a release. You can test this out using the instructions in the README or wait for the next publish soon.

See https://github.com/mysqljs/mysql/issues/2003#issuecomment-400409568

Duplicate of #2003

**Closed by dougwilson** 2018-06-27 20:20 UTC
