### ISSUE TITLE
Please implement the CAST AS JSON

### ISSUE THREAD

**Issue by petkovic43** [mysqljs/mysql#1833] opened 2017-09-26 17:24 UTC
the result of the grouping below is being returned as a string, rather than a json object. In mysql2 this works fine, however I would like to continue using mysql.

`CAST("[", GROUP_CONCAT(JSON_OBJECT("id", xxx.id, "name", xxx.name), "]") AS JSON) AS myItem`

**Comment by yunchiri** [comment] 2017-09-30 14:52
CAST( CONCAT( "[", GROUP_CONCAT(JSON_OBJECT("id", xxx.id, "name", xxx.name)), "]") AS JSON) AS myItem

is ok?

**Comment by petkovic43** [comment] 2017-10-02 12:01
Hi, now that I realized that I wrote the sentence in the wrong way, CONCAT was missing. However, this statement is not returning a json object, but a string. As below:

```
{
    myItem: '[{"id": 1, "name": "myName1"},{"id": 2, "name": "myName2"}]'
}
```

**Comment by dougwilson** [comment] 2017-10-03 15:53
It's on the radar to work on. There is a PR I'm working to clean up. It'll have to be opt-in because code is already out there that is expecting a string back and running through `JSON.parse` themselves. You can always define a custom `typeCast` function which can parse it for you as well, which is also what people have been doing.

https://github.com/mysqljs/mysql/issues/1267#issuecomment-230739821 is how you can do this.

Duplicate of #1267 (to keep tracking this in one ticket).

**Closed by dougwilson** 2017-10-03 15:53 UTC
Labels: feature
