### ISSUE TITLE
load data local infile callback not fired

### ISSUE THREAD

**Issue by chacent** [mysqljs/mysql#2144] opened 2018-12-05 09:27 UTC
I've encountered a problem lately with LOAD LOCAL DATA INFILE

The functionality works, and rows are added fine to MySQL, but the callback never gets called, and the code hangs. This doesn't seem to always reproduce, but rather "comes and goes", mostly based on the dataset.

A wireshark trace shows that MySQL responds with an OK packet after the LOAD command most times,but sometimes okpacket is not  send, it's hard to reproduce,so i can't know why.

**Comment by dougwilson** [comment] 2018-12-05 23:42
Hi @chacent I'm sorry you're having this issue. I can try to poke at it / stare down the source code to see if I can determine anything, but cannot make any promises without some kind of way to reproduce the issue.

**Comment by chacent** [comment] 2018-12-06 01:30
big dataset,and mutil time can repeat the problem

**Comment by chacent** [comment] 2018-12-06 01:35
https://github.com/mysqljs/mysql/issues/593#issue-19607038,
same problem

**Comment by dougwilson** [comment] 2018-12-06 01:37
Hi, I'm not saying there is not an issue here, just that it is going to be difficult to figure out without a reproduction case. I will try to look into it as soon as I can, but just without a reproduction case I can't even know I'll be able to reproduce it because there are so many variables involved.

**Comment by chacent** [comment] 2018-12-06 01:39
i think this's protocol issue,may some case that okpacket not must?

**Comment by chacent** [comment] 2018-12-06 01:42
can i speak chinese?

**Comment by dougwilson** [comment] 2018-12-06 01:46
From my understanding of the protocol ad documented by Oracle (https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-COM_QUERY_Response) the path for INFILE will always end by the server sending back either an OK packet or an ERROR packet after the client sends the empty packet (and the data has completed insert operations).

You can write Chinese here, but since I don't understand it, I will need to run it through a translator, which may or may not do it justice.

**Comment by chacent** [comment] 2018-12-06 02:01
问题是这样的，我从sqlserver数据库转换到mysql数据库，每个数据表单独传输（每个表数据都非常大），我重载了_sendLocalDataFile的实现，因为你们的代码会耗尽内存（没有使用流机制）。当传输结束时，我手动发送了EmptyPacket。this.emit('packet', new Packets.EmptyPacket());服务器已经接受了这批数据，但是callback没有被调用，我抓包尝试，但是不能容易的截取到这种问题。我只抓到了一次，但没有保存。我开启了调试，每次调试都没有收到okpacket，并且抓包也确实没有收到okpacket，但我还不确定是不是这样。目前我认为代码本身没有问题，问题出在是不是一定会有okpacket上，我还没有足够的精力来做大量的测试，我怀疑用同一批数据多次调用也可以重现这个bug,我会尽量抽时间来确定这个事情

**Comment by chacent** [comment] 2018-12-06 02:03
--> (270) ComQueryPacket
ComQueryPacket {
  command: 3,
  sql: 'load data local infile \'\' replace into table `t_well` fields terminated by \',\' enclosed by \'\\\'\' escaped by \'\\\\\' lines terminated by \'\\n\' (str_id,str_course,date_confirm)' }

<-- (270) ResultSetHeaderPacket
ResultSetHeaderPacket { fieldCount: null, extra: undefined }

........


--> (270) EmptyPacket
EmptyPacket {}

now hangs

**Comment by dougwilson** [comment] 2019-02-06 03:41
Hi @chacent I haven't been able to reproduce so far, so I have no idea what else to tell you. As I linked above, the point at which you are hanging is when the server needs to send back the file path for this module to send the contents of. There really doesn't seem like there is an issue with this module, right? I also haven't been able to get the driver to hang as you show, which makes it pretty much not possible for me to progress further.

**Comment by dougwilson** [comment] 2019-03-08 01:50
I'm going to close this since there hasn't been any follow up with a reproduction case for me to debug.

**Closed by dougwilson** 2019-03-08 01:50 UTC
Labels: needs more info

**Comment by annjawn** [comment] 2019-05-29 15:25
@dougwilson is it possible to add some usage documentation for LOAD DATA? Is the usage similar to any regular MySQL statement?
