### ISSUE TITLE
pointer being freed was not allocated

### ISSUE THREAD

**Issue by pod4g** [mysqljs/mysql#1741] opened 2017-05-29 11:53 UTC
*Node Version*: 7.10.0
*Mysql Version*: 2.13.0
*Platform*: macOS Sierra 10.12.5

I have a file that contains 9000+ lines，read this file by `createReadStream` line by line，every line is a json，I parse this json and insert the data to database，and 110000+ SQLs will execute，

but i get this error :
> node(92378,0x1025313c0) malloc: *** error for object 0xfffffffc: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
[1]    92378 abort      NODE_ENV=dev node src/crawler/insertMetaAndImage.js

I have 16G  memory~ when the error occur, the memory only used 8G-, 

and  every connection of [mysql](https://www.npmjs.com/package/mysql) was release correctly

what's wrong?

Forgive my broken English！

thanks for any reply

**Comment by pod4g** [comment] 2017-05-29 11:53
The code of `insertMetaAndImage .js` like this (reduce many code):

```javascript
const lineReader = require('readline').createInterface({
    input: require('fs').createReadStream(
      file || path.resolve('./src/crawler/data', 'ajson.5')
    ),
    output: process.stdout,
    terminal: false
  })


 lineReader.on('line', json => {
    let article = JSON.parse(json)
    const { images, aid } = article
    DB.exec(
      `DELETE FROM tableName WHERE aid = ${aid}`
    ).then(data => {
       for (let image of images) {
         DB.exec(`INSERT INTO tableName SET ?`, image).then(data => {
            console.log(`the ID ${aid} insert success ....`)
          })
          .catch(err => {
            console.log(err)
          })
       }
   })
 })
```

**Comment by dougwilson** [comment] 2017-05-30 01:04
Hi @pod4g I don't think that error would be caused by this module, because it is pure JavaScript; there is no C++ or C component of this module to cause an error like that. I can maybe try and debug, but would need the complete code to run to reproduce, including the complete contents of the file that it is trying to read and the DDL to setup my MySQL instance to have a successful run.

**Comment by dougwilson** [comment] 2017-06-29 04:47
Closing since I never heard back.

**Closed by dougwilson** 2017-06-29 04:47 UTC
Labels: needs more info
