### ISSUE TITLE
Query result is array of RowDataPackets instead of array of objects

### ISSUE THREAD

**Issue by lusvelt** [mysqljs/mysql#1899] opened 2017-12-13 13:03 UTC
The issue is very simple, when I retrieve data from the database, I expect it to be an array of objects, while it is an array of rowDataPackets. IWhat shall I do to make the promise resolve with an array of objects instead of an array of RowDataPackets?

```javascript
const mysql = require('mysql');

const databaseConnection = require('./database_connection')

var con = mysql.createConnection(databaseConnection);

con.connect(function(err) {
  if (err) throw err;
  console.log('Connected to mysql database');
});

var queries = {
  users: 'SELECT * FROM users'
};

const getList = (queryName, queryParams) => {
  return new Promise(function(resolve, reject){
    con.query(queries[queryName], queryParams, function(err, result, fields){
      if (!err) resolve(result); // Here it is the array of RowDataPackets
      else reject(err);
    });
  });
};

module.exports = {
  getList
};
```

**Comment by crimsonhawk009** [comment] 2017-12-15 18:39
This seems like a hacky solution but to stringify the results and parsing them works. If there is a better solution I would like to hear it.
```js
[ RowDataPacket {
    userId: 3,
    fullname: 'John Smith',
    username: 'jsmith0829',
    email: 'jsmith@example.com' },
  RowDataPacket {
    userId: 5,
    fullname: 'Mary Smith',
    username: 'maryisawesome',
    email: 'maryisawesome@example.com' } ]

```
```js
const mysql = require('mysql');

const databaseConnection = require('./databaseConnection');

var con = mysql.createConnection(databaseConnection);

con.connect(function(err) {
	if (err) throw err;
	console.log('Connected to mysql database');
});

var queries = {
	users: 'SELECT * FROM users'
};

const getList = (queryName, queryParams) => {
	return new Promise(function(resolve, reject){
		con.query(queries[queryName], queryParams, function(err, result, fields){
			if (!err) resolve(JSON.parse(JSON.stringify(result))); // Hacky solution
			else reject(err);
		});
	});
};

module.exports = {
	getList
};
```
```js
[ { userId: 3,
    fullname: 'John Smith',
    username: 'jsmith0829',
    email: 'jsmith@example.com' },
  { userId: 5,
    fullname: 'Mary Smith',
    username: 'maryisawesome',
    email: 'maryisawesome@example.com' } ]
 

```

**Comment by dougwilson** [comment] 2017-12-15 19:12
Hi! I'm a little confused on what the issue is here, can someone help me understand a bit? The title says you get RowDataPackets instead of objects, but RowDataPackets are JavaScript objects. I'm sure you have some specific meaning behind what the difference is to you, can you explain?

There is no current way, though, to change the results from a query currently. It will always be an array of objects right now. Are you asking for it to be an array of arrays (a common request, which is why I'm thinking maybe that is what you're asking)?

**Comment by crimsonhawk009** [comment] 2017-12-15 20:30
I do not know about the original poster but earlier today I was having an issue referencing an object in a for loop from a query. I must of had a different problem as I am getting it to work fine now without any stringify or parse.

**Comment by dougwilson** [comment] 2017-12-28 21:19
Thanks, @crimsonhawk009 . Sounds like I can close this issue for you 👍

**Closed by dougwilson** 2017-12-28 21:19 UTC
Labels: needs more info

**Comment by jclem** [comment] 2020-03-31 23:27
I believe the problem here is that `RowDataPacket` is an object, but it's not a "plain" object. It has a prototype associated with it, etc, and isn't JSON-serializable as-is.

**Comment by wmelton** [comment] 2020-07-29 21:25
@lusvelt & @crimsonhawk009 - a simple map function can take care of this too. Assuming results is your query results.

```
return await results.map((result) => ({
    ...result,
  }));
```

**Comment by Dr4kn** [comment] 2021-02-22 23:24
[Here](https://github.com/mysqljs/mysql/issues/1330#issuecomment-171337005) is the elegant solution from the developer:

`console.log(JSON.stringify(result))`

**Comment by LucAngevare** [comment] 2021-05-02 14:21
May I ask why MySQL returns this form of object? It seems really obscure and unnecessary to force the people using the JavaScript module at the very least to have to parse the `RowDataPacket` "object" by stringifying and parsing, mapping or assigning an object to it, when it could just as easily just return an object. I don't really see a reason or any benefits for the return value being the way that it is, and even if there are benefits it's just as easy to make the people that need it just do `const stringObj = "RowDataPacket" + JSON.stringify(result[RowDataPacket])` instead of making everyone needing it as normal write more code, I feel like there's way more people that would rather have it return a normal form of object than there are people needing it to return this form, and I just don't see any reason for it returning anything in this format. Thanks!

**Comment by arubin02** [comment] 2022-01-08 18:54
I am very new to Javascript and have just run in to this problem.
What I have found is that the RowDataPacket is actually a JSON Object. You are getting an array of these objects so in your example the values in the individual fields can be retrieved simply as 
result[0].fullname // which will get you John Smith
result[0].username // jsmith8029
result[1].fullname // Mary Smith
