### ISSUE TITLE
Can't get this running. Keep getting auth error

### ISSUE THREAD

**Issue by Slyke** [mysqljs/mysql#2022] opened 2018-05-22 05:09 UTC
Hello, not sure if this has been reported or if it's just my local environment. I'm running MySQL inside Docker for Windows.

I'm using the latest docker image for MySQL and latest MySQL npm package. To simplify things, I've copied the code from the readme, but when I try to connect, I keep getting: 

```
mysql-test  |   { Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
mysql-test  |     **** REMOVED STACK TRACE ****
mysql-test  |   code: 'ER_NOT_SUPPORTED_AUTH_MODE',
mysql-test  |   errno: 1251,
mysql-test  |   sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
mysql-test  |   sqlState: '08004',
mysql-test  |   fatal: true }
```

**Comment by sidorares** [comment] 2018-05-22 06:00
thanks, already reported. Duplicate of #2002
Work to fix this happen in #1962

**Closed by sidorares** 2018-05-22 06:00 UTC
