### ISSUE TITLE
Question about Connection Charset

### ISSUE THREAD

**Issue by bekihm** [mysqljs/mysql#1851] opened 2017-10-26 08:12 UTC
Hello,
we have in our project the problem that the sql database which we would reach could have Latin1 encoding. But the client which uses the 'mysql'-module uses for the connection the default UTF-8 encoding. Now we have the problem that the client receives umlauts not correctly.
Currently we have a solution to connect a first time to the database to find out which encoding is used there. Then we connect again with the right database encoding. 
This fact is very confusing for us because we thought that the database should convert the data automatically depending on the client connection. Is there a better solution for it?

**Comment by kai-koch** [comment] 2017-10-26 12:38
Please make sure the umlauts are NOT already corrupted on the remote-database server to exclude a faulty Import from a database dump. (Use the original mysql-client from the server-console or some other frontend to check that.)

If the database is not already corrupted, it doesn't matter which charset the databse uses, as long as you set the correct client-side charset. The server takes care of converting the charset from the server-side encoding to the client-side encoding. Unless you use an older server-version (below 5.5.3).

In some configurations you need to set the client charset explicit for each of your connections.
Either use the mysqljs Connection option "charset" 
or you could execute the following queries once as first statements of each connection.

```SQL
SET character_set_client='utf8mb4';
SET character_set_connection='utf8mb4';
SET character_set_results='utf8mb4'
SET NAMES utf8mb4;
```
For MySQL-server-versions below 5.5.3, you need to use 'utf8' instead of 'utf8mb4', because 'utf8mb4' got first introduced in version 5.5.3.

Please close the issue if my answer solves your problem.

If it does not, please provide more information, so we can reproduce this behaviour:

* version of MySQL-Server
* version of Nodejs
* version of mysqljs
* some sample code
* database structure
* a small sample dataset

**Comment by bekihm** [comment] 2020-09-17 16:57
"If the database is not already corrupted, it doesn't matter which charset the databse uses"
Thanks for the detailed answer. That was the point. We had to repair our data in the database.

**Closed** 2020-09-17 16:57 UTC
