### ISSUE TITLE
Batch mode slowing down query

### ISSUE THREAD

**Issue by goodfella1408** [mysqljs/mysql#1866] opened 2017-11-09 14:51 UTC
mysqljs version 2.X (tried on 2.15,2.8,2.0,2.1)

I run a query (without using streams) which returns around 10K rows .This query returns in 3-4 seconds but for  a particular time range this query is taking 180+ seconds .The number of bytes and rows returned for this time range is same (10K rows) .The same query when run on mysql workbench takes 3-4 seconds only .
On enabling debug logs in mysqljs I see the slow running query gets a batch of rows ,waits and starts again -

<-- RowDataPacket
{ row_1: 'val_1',
  row_2: val_2,
  row_3: val_3}

<-- RowDataPacket
{ row_1: 'val_4',
  row_2: val_5,
  row_3: val_6}
.
.
.
.
.
.
<waits for around 15 seconds>
starts again.

This is leading to almost 60x increase in time .Queries for other time ranges get all the rows in a single burst .
Is there a way I can change/control this behavior through a config or code changes ?

**Comment by dougwilson** [comment] 2017-11-09 14:54
There is no batch behavior coded into this module, so I don't know whay you are referring to. Can you point to where in the source code this barch mode is? Maybe we know it by a different name or something.

**Comment by goodfella1408** [comment] 2017-11-09 15:03
I have not had the chance to look at the source code but I was suspecting the module switches to a batch mode given the log pattern - a burst of RowDataPacket's , wait time and then the next burst .

**Comment by dougwilson** [comment] 2017-11-09 15:06
Gotcha. There isn't any such mode or code in this module I'm aware of, so really have no idea why that would happen. If you can provide all the following so I can reproduce the issue, I can debug through the issue to see what is going on internally:

1. Version of this module
2. Version of Node.js
3. Version of your MySQL server
4. Complete code that can just be pasted and run.
5. DDL and data to load in order to support the queries in the code and reproduce the issue
6. Instructions on how to setup, how to run, and what you see / what you're expecting to see.

Thanks!

**Comment by goodfella1408** [comment] 2017-11-09 19:08
Mysql version is 5.6
Node version v4.7.2
Version of mysqljs 2.14.1
Came across a very strange behavior ->
A query containing the clause
BETWEEN '2017-11-09T00:00:00.000Z' AND '2017-11-09T00:30:59.999Z'
took nearly 3 minutes on this module with mysql scanning 400 million rows !
# Query_time: 188.565439 Lock_time: 0.000192 Rows_sent: 10801 Rows_examined: 484872297

The same query in mysql workbench took less than 3 seconds .

Increasing the date range makes the query work on the mysqljs module
BETWEEN '2017-11-07T00:00:00.000Z' AND '2017-11-09T00:30:59.999Z'
with mysql scanning around 4 million rows
 # Query_time: 2.908461 Lock_time: 0.000313 Rows_sent: 10832 Rows_examined: 4274901

I tried various versions of the query like CAST but to no avail
BETWEEN CAST ('2017-11-09T00:00:00.000Z' AS datetime) AND CAST ('2017-11-09T00:30:59.999Z' AS datetime)
In my case rounded up dates could also be used and converting the query to 
BETWEEN '2017-11-09' AND '2017-11-09' 
brought down the execution time to 3 seconds !

**Comment by goodfella1408** [comment] 2017-11-09 19:12
@dougwilson thanks for the fast response .Ill find some time and try to create the setup for you where this issue can be replicated

**Comment by dougwilson** [comment] 2017-11-09 19:12
All this module does is send the query text to SQL. I can try to debug it for you, just need to be able to reproduce it, otherwise I don't really have any idea why this would be happening.

**Comment by kai-koch** [comment] 2017-11-10 09:19
If you run the query first in Node and then in Workbench, it seems workbench got the result from the mysql-server query cache.

Run a new query with different timestamps, work bench first then the exact query string in Node, the  time taken should be reversed.

It seems to me the mysql-server does a table scan for your query (It reads all rows from the harddisk to determin, if a row goes into the result set.)
Have you created an index for the date field? Over 400 million rows without an index means a lot of harddisk I/O and it takes, depending on your hardeware, a few minutes to execute the query.

The type-casting you did took place on the server-side and your examples so far, leads me to believe, this is a server or DB-Schema issue not an issue with mysqljs.

**Comment by goodfella1408** [comment] 2017-11-10 09:55
Issue is persistent on mysqljs - running 5 queries on mysqljs and 5 on workbench in random order always results in mysqljs taking 180+ seconds and workbench taking 3+ seconds.
Field is indexed and even casting did not help.Changing 2017-11-09T00:00:00.000Z to 2017-11-09 worked

**Comment by dougwilson** [comment] 2017-12-15 19:21
Thanks for the follow up. I'm going to close it on our end because no reproduction steps have materialized thus far for us to have something to look into.

**Closed by dougwilson** 2017-12-15 19:21 UTC
Labels: needs more info
