### ISSUE TITLE
Unable to create Mysql connection through Vm

### ISSUE THREAD

**Issue by NishiBangar** [mysqljs/mysql#1846] opened 2017-10-18 09:52 UTC
I have been working on a process, where i do require to establish connection to **MySQL** from **Virtual environment**.

**Note:** For Virtual environment, i am using [vm2](https://github.com/patriksimek/vm2) module and for MySQL i am using [mysqljs](https://github.com/mysqljs/mysql) module respectively.

Unfortunately i have been faced with an error stating the following and evidently, the connection is not established.
     
    'set' on proxy: trap returned falsish for property 'destroy'

Kindly, consider this issue, or let me know of any such methodologies with respect to working with mysql in vm.

Below are the sample code.

**Sandbox Script** - sandboxScript.js
````javascript
(function() { 
	 console.log("Sandbox Environment");
........
........
........
	 const MysqlConnector = require(sandboxModulesPath+'/mysql_object');	 

	 var mySqlObject= new MysqlConnector ('mySQLRemoteName'); /*Instantiate MysqlConnector class by passing a mySQL endpoint name to its constructor*/

........
........
........

 })();
````

**Node Vm Configuration** - vmConfig.js
````javascript
.......
.......
.......
//**** Read Sandbox helper script ****
var helper = fs.readFileSync(__dirname + '/../sandbox/sandboxScript.js', { encoding: "utf8" });
const {NodeVM, VMScript} = require('vm2');
            const vm = new NodeVM({
                sandbox: {
                    sandboxModulesPath : __dirname + '/../sandbox',
                    request : currentRequestObj,
                    remoteSets: apiRemoteEndpointList,  /*All Remote Endpoints Specific to the API*/
                    script: {
                        userScript: userScript
                    } 
                },
                require: {
                        context: 'sandbox',
                        external: ['lodash','mysql','async','@mysql/xdevapi','bignumber.js','safe-buffer','readable-stream','process-nextick-args','isarray','core-util-is','inherits'],
                        builtin: ['url','querystring','crypto','events','net','tls','buffer','util','fs','stream','assert','os','path'],  
                        root: "./"
                    }
             });
            try{
                var result = vm.run("module.exports = "+helper,'vmConfig.js');
                callback(null, result);
            }
            catch(e){
                console.log("Sandbox Error");
                console.log(e);
                callback(null, e.message);
            } 
.......
.......
.......
````
**Establish MySQL connection in Vm envrionment** - mysql_object.js
````javascript
var remotemysql = require('mysql');

function MysqlObject(remoteEndPoint){
	this.remoteEndPoint = remoteEndPoint;
	this.pool = new Object();
	this.connection = new Object();

	console.log("Create Pool")
       /**********************************************************
       ******* This is the part where error is encountered ******
       **********************************************************/
	this.pool = remotemysql.createConnection({                                       
		host: 'localhost',
		port: 3306,
		user: 'root',
		password: 'root',
		database: 'dummyDB'
	});
	console.log("End of Create Pool");
}

module.exports = MysqlObject
````

**Comment by kai-koch** [comment] 2017-10-18 13:52
As I read your code, you create a **connection** and assign it to ```MysqlObject.pool```.
I think you either need to assign it to ```MysqlObject.connection``` or need to use ```mysql.createPool()``` .
See [Pooling connections](https://github.com/mysqljs/mysql#pooling-connections)

**Comment by NishiBangar** [comment] 2017-10-19 09:27
@kai-koch , I tried the suggested approaches as well, but no positive outcome. I am thrown with the same error.

    'set' on proxy: trap returned falsish for property 'destroy'
**Approach 1**
````javascript
var mysql = require('mysql');
var pool  = mysql.createPool({
  connectionLimit : 10,
  host: 'localhost',
  port: 3306,
  user: 'root',
  password: 'root',
  database: 'dummyDB'
});

pool.query('SELECT 1 + 1 AS solution', function (error, results, fields) {
  if (error) throw error;
  console.log('The solution is: ', results[0].solution);
});
````
**Approach 2**
````javascript
var mysql = require('mysql');
var pool  = mysql.createPool({
   host: 'localhost',
   port: 3306,
   user: 'root',
   password: 'root',
   database: 'dummyDB'
});

pool.getConnection(function(err, connection) {
  if (error) {
	  	throw error;
   }
   console.log("Connection created");
});
````

**Comment by kai-koch** [comment] 2017-10-19 15:07
I am not familiar with vm2, but in the docs it says " ...  to **synchronously** run an untrusted code ..."

Are you sure you can put an **asynchronous** module like mysqljs inside the nodeVM scope?
After reading the docs, I am not sure you can instantiate mysqljs from inside the VM. The error message indicates an property/method no longer exists, which works as designed, if you can only run synchronous code inside the VM.

My best guess would be you have to instantiate a connection or pool object and inject it from the outside into the VM, but that would still not do for the asynchronous behavior of mysqljs. For that you would need to have a wrapper, that makes mysqljs seem to run synchronous, while it does it work its magic asynchronous in the background.
If you can use an asynchronous module inside the VM, are you sure mysqljs can access all needed dependencies, build in or external?

**Comment by dougwilson** [comment] 2017-10-21 05:41
If you look at the stack trace (if you provided it, it would have been a quicker response), the issue is in the `readable-stream` module, not this module:
```
$ node test.js
Sandbox Environment
Create Pool
Sandbox Error
TypeError: 'set' on proxy: trap returned falsish for property 'destroy'
    at node_modules\readable-stream\lib\_stream_readable.js:210:28
    at Object..js (node_modules\vm2\lib/sandbox.js:72:5)
    at _require (node_modules\vm2\lib/sandbox.js:258:24)
    at node_modules\readable-stream\readable.js:12:30
    at Object..js (node_modules\vm2\lib/sandbox.js:72:5)
    at _require (node_modules\vm2\lib/sandbox.js:258:24)
    at node_modules\mysql\lib\protocol\sequences\Query.js:7:20
    at Object..js (node_modules\vm2\lib/sandbox.js:72:5)
    at _require (node_modules\vm2\lib/sandbox.js:258:24)
    at node_modules\mysql\lib\protocol\sequences/index.js:4:17
```

I assume there is something you need to whitelist for vm2 still. Here is a reproduction case without this module at all:
```
>node -pe "NodeVM=require('vm2').NodeVM;new NodeVM({require:{context:'sandbox',builtin:['stream','events','buffer','util'],external:['readable-stream','process-nextick-args','isarray','safe-buffer','core-util-is','inherits']}}).run(`console.log(require('readable-stream'))`,'foo.js')"

node_modules\vm2\lib\main.js:428
                        throw this._internal.Decontextify.value(e);
                        ^
TypeError: 'set' on proxy: trap returned falsish for property 'destroy'
    at node_modules\readable-stream\lib\_stream_readable.js:210:28
    at Object..js (node_modules\vm2\lib/sandbox.js:72:5)
    at _require (node_modules\vm2\lib/sandbox.js:258:24)
    at node_modules\readable-stream\readable.js:12:30
    at Object..js (node_modules\vm2\lib/sandbox.js:72:5)
    at _require (node_modules\vm2\lib/sandbox.js:258:24)
    at Object.<anonymous> (foo.js:1:75)
    at NodeVM.run (node_modules\vm2\lib\main.js:426:27)
    at [eval]:1:218
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
```

**Closed by dougwilson** 2017-10-21 05:41 UTC
Labels: help wanted, question

**Comment by dougwilson** [comment] 2017-10-21 05:56
Trying to debug this looks like it's actually some kind of bug in `vm2` itself. There is an issue https://github.com/patriksimek/vm2/issues/101 which isn't this module, but seems like the same underlying bug. I tried to just replicate what `readable-stream` is doing but cannot trigger the issue. The `vm2` code uses `Proxy`s a lot and I really don't know what is going on, so probably need the `vm2` folks to see what the issue is.

I see you filed https://github.com/patriksimek/vm2/issues/101 already.

**Comment by dougwilson** [comment] 2017-10-21 05:56
The issue https://github.com/patriksimek/vm2/issues/100 also sounds similar, since that's where `readable-stream` is failing: trying to extend a built-in object.
