### ISSUE TITLE
Getting duration time on queries

### ISSUE THREAD

**Issue by MicroCheapFx** [mysqljs/mysql#1643] opened 2017-02-14 09:39 UTC
It would be nice to be able to retrieve duration/fetching time on queries.
I am actually benchmarking stuffs with mysql and being able to script it with nodejs would be helpful.

**Comment by dougwilson** [comment] 2017-02-14 14:01
Absolutely and PRs are welcome to implement the feature! I believe this is a duplicate of #483 , but let me know if that's incorrect and I can re-open (and I guess add how they're different so I can understand the ask better :) ).

**Closed by dougwilson** 2017-02-14 14:01 UTC
