### ISSUE TITLE
dateStrings and typeCast

### ISSUE THREAD

**Issue by xycloud** [mysqljs/mysql#1556] opened 2016-10-25 02:45 UTC
event when dateStrings set as true, typeCast will still convert datetime string as date object

**Comment by dougwilson** [comment] 2016-10-25 03:05
Hi @xycloud, unfortunately I cannot reproduce and our tests show it working just fine. Can you provide additional information to look into the issue? Please provide all the following:

1. Version of Node.js you are using.
2. Version of this module you are using.
3. Complete code I can copy and paste and run that reproduces the issue.
4. Instructions for how to run the code with a description of what happens with the issue and what you are expecting to happen.

Thank you!

**Comment by bbito** [comment] 2016-10-25 19:01
@xycloud - One thing that may be confusing - and which I didn't realize until I started creating a test for a PR - is that this module will accept either a string OR Date object to send to MySQL. The `dateStrings` connection option affects how values are returned from MySQL. This behavior can be seen in the test I have attached to a pending PR: https://github.com/bbito/node-mysql/blob/master/test/integration/connection/test-datestrings-options.js

**Comment by dougwilson** [comment] 2016-11-01 16:59
Hi @xycloud I'm going to close this issue since there hasn't been any response.

**Closed by dougwilson** 2016-11-01 16:59 UTC
