### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mpavithra240** [mysqljs/mysql#2162] opened 2019-01-07 03:42 UTC
/Users/pavithra.m05/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (/Users/pavithra.m05/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/pavithra.m05/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/Users/pavithra.m05/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/Users/pavithra.m05/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/Users/pavithra.m05/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/pavithra.m05/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/pavithra.m05/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    --------------------
    at Protocol._enqueue (/Users/pavithra.m05/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/pavithra.m05/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/Users/pavithra.m05/node_modules/mysql/lib/Connection.js:118:18)
    at Object.<anonymous> (/Users/pavithra.m05/Documents/node/DBModule.js:21:8)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)

**Comment by sidorares** [comment] 2019-01-07 03:53
hi @mpavithra240 , this is duplicate of #2002 . See #1962 to track progress of new auth implementation. As a temporary solution you can change auth mode back to pre-mysql8 ( example: https://github.com/mysqljs/mysql/issues/1507#issuecomment-242885003 )

**Closed by sidorares** 2019-01-07 03:53 UTC
