### ISSUE TITLE
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server

### ISSUE THREAD

**Issue by diogocsc** [mysqljs/mysql#2237] opened 2019-06-14 14:36 UTC
F:\Projetos\Papo A Papo\in between>node mysql_boot.js
Could not establish a connection to the database
F:\Projetos\Papo A Papo\in between\mysql_boot.js:55
        throw error;
        ^

Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protoc
ol requested by server; consider upgrading MySQL client

**Comment by Spike-86** [comment] 2019-06-16 19:02
+1 Me to (((

**Comment by dougwilson** [comment] 2019-06-16 19:07
I am working on getting some of this support added now. But if you can say which specific plugin you user is using, I can make sure your specific case is supported before closing the issue after plugin support is added.

**Comment by eyedean** [comment] 2019-06-17 00:10
Hi @dougwilson, 

Is there a chance that we get https://github.com/mysqljs/mysql/pull/1962/ (or basically `caching_sha2_password` as default auth plugin of MySQL 8) anytime soon in here?

_Background:_ I found tens of issues here asking for this functionality since at least three years ago, and the only one that I found with some progress was https://github.com/mysqljs/mysql/issues/1959 by @ruiquelhas which was pending your volunteer work to fix/rebase [on Sep 2018](https://github.com/mysqljs/mysql/pull/1962#issuecomment-424321907) and by now is [69 commits behind master](https://github.com/ruiquelhas/mysql/tree/feature/caching-sha2-password).

I thought maybe that's fallen off from your list, so I moved to [MySQL Connector/Node.js with X DevAPI by MySQL](https://github.com/mysql/mysql-connector-nodejs), which I think is led by Rui.  Unfortunately their documentation (on the Node.js) is not as detailed, and more importantly there is no Typescript support (definition file) on their package.

So after one week of moving around, and trying so many different solution for my not-so-uncommon stack of TS+Node+MySQL8, I just saw your message here and it made me hopeful that I might be able to get what I want, here!  

Thanks, anyways. :)

**Comment by dougwilson** [comment] 2019-06-17 00:41
Hi @eyedean that's what I'm referring to above when I said I am working to get this in currently. The PR with all the issues addressed just came in less than 1 week ago... (5 days ago) #2233

But unless you can tell me if that will resolve the issue @diogocsc is having, your comment is likely off topic for this issue. I don't want to close @diogocsc issue if they are using a different plugin...

**Comment by diogocsc** [comment] 2019-06-17 10:04
I worked around the issue by reinstalling MySQL8.0 in legacy mode.

**Comment by eyedean** [comment] 2019-06-17 17:43
So my comment wasn't "off-topic" @dougwilson.  As @diogocsc's problem was the default auth plugin of MySQL 8 (i.e. [`caching_sha2_password`](https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html)) as I mentioned.

**Comment by dougwilson** [comment] 2019-06-17 17:59
Duplicate of https://github.com/mysqljs/mysql/issues/1959

**Closed by dougwilson** 2019-06-17 17:59 UTC
